// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzihbi_sn3H5BQlObHFUWNfIqWvRlFtuc',
    appId: '1:339882831473:web:27a03f319ecfb0bfdeb5d0',
    messagingSenderId: '339882831473',
    projectId: 'body-improvement-club',
    authDomain: 'body-improvement-club.firebaseapp.com',
    storageBucket: 'body-improvement-club.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6o6TVaTRkUEYHmc1N_65XqkYVbFH6qY',
    appId: '1:339882831473:android:19cd2068fbbb4a15deb5d0',
    messagingSenderId: '339882831473',
    projectId: 'body-improvement-club',
    storageBucket: 'body-improvement-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKV1TdPTSQW4FDEz7ewh6BCQrD7gIGccU',
    appId: '1:339882831473:ios:1beb86402d24cb29deb5d0',
    messagingSenderId: '339882831473',
    projectId: 'body-improvement-club',
    storageBucket: 'body-improvement-club.appspot.com',
    iosBundleId: 'com.BICApp.bicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKV1TdPTSQW4FDEz7ewh6BCQrD7gIGccU',
    appId: '1:339882831473:ios:339421288c8721bbdeb5d0',
    messagingSenderId: '339882831473',
    projectId: 'body-improvement-club',
    storageBucket: 'body-improvement-club.appspot.com',
    iosBundleId: 'com.BICApp.bicApp.RunnerTests',
  );
}
